wip2: lotus container rendering

diff --git a/charts/lotus-lib/values.yaml b/charts/lotus-lib/values.yaml
--- a/charts/lotus-lib/values.yaml
+++ b/charts/lotus-lib/values.yaml
@@ -1,29 +1,24 @@
-lotusVolumeMounts: &lotusVolumeMounts
+common:
+  image: &lotusImage
+    repository: filecoin/lotus-all-in-one
+    tag: latest
+    imagePullPolicy: Always
+  lotusVolumeMounts: &lotusVolumeMounts
     # XXX: Update this to lotus-data once this is stable
-  - name: lotus-path
+  - &lotusPathVolumeMount
+    name: lotus-path
     mountPath: /var/lib/lotus
     # XXX: Update this to lotus-parameters once this is stable
   - name: parameter-cache
     mountPath: /var/tmp/filecoin-proof-parameters
 
-# common:
-#   lotus:
-#     ...
-
-#   volumeMounts:
-#     # XXX: Update this to lotus-data once this is stable
-#   - name: lotus-path
-#     mountPath: /var/lib/lotus
-#     # XXX: Update this to lotus-parameters once this is stable
-#   - name: parameter-cache
-#     mountPath: /var/tmp/filecoin-proof-parameters
-
 lotus:
   name: lotus
-  image:
-    repository: filecoin/lotus-all-in-one
-    tag: latest
-    imagePullPolicy: Always
+  image: *lotusImage
+  command: [ "bash", "-c" ]
+  ports:
+  - containerPort: 1234
+    name: lotus-api
   resources:
     requests:
       memory: 64Gi
@@ -41,166 +36,268 @@ lotus:
         memory: 32Gi
         cpu: 16
 
-  volumeMounts:
-  - name: lotus-path
-    mountPath: /var/lib/lotus
-    # XXX: Update this to lotus-parameters once this is stable
-  - name: parameter-cache
-    mountPath: /var/tmp/filecoin-proof-parameters
-    # <<: *lotusVolumeMounts
-# lotus configuration
-# By default, lotus will run as a full-node. In this mode, it will take
-# time to sync the block chain and additiona resources will be needed
-# to keep it in sync.
-# Lotus can also be run as a lite-node. In this mode, wallets are local
-# and lotus clients connect to the same lotus-lite node, but messages
-# must be passed to a back-end lotus node. The backend can be a fullnode
-# or gateway service you run yourself or a public endpoint
-#
-# note:
-# api.chain.love is a lotus-gateway instance managed by Protocol Labs.
-# It provides a limited set of lotus API endpoints.
-lotus:
-  enabled: true
-  lite:
-    enabled: false
-  image: filecoin/lotus-all-in-one:nightly
-  imagePullPolicy: Always
-  reset:
-    enabled: false
-    percent: 90
+  volumeMounts: *lotusVolumeMounts
+
+reset-datastore:
+  name: reset-datastore
+  image: *lotusImage
+  command: [ "bash", "-c" ]
+  args:
+  - |
+    set -xeou pipefail
+    pct=$(df -h $LOTUS_PATH | awk '/[0-9]+%/ {print substr($5, 1, length($5)-1)}')
+    echo "reset percentage is $RESET_PERCENTAGE"
+    echo "The datastore is $pct% full"
+    if [[ "$pct" -lt "$RESET_PERCENTAGE" ]]
+    then
+      echo "not resetting"
+    else
+      echo "resetting datastore."
+      rm -rf "${LOTUS_PATH}/datastore" || echo "datastore does not exist"
+    fi
   env:
-    FILECOIN_PARAMETER_CACHE: "/var/tmp/filecoin-proof-parameters"
-    LOTUS_PATH: "/var/lib/lotus"
-    ## FULLNODE_API_INFO: must be set when lotus.lite.enabled is true
-    # FULLNODE_API_INFO: "wss://api.chain.love"
+    LOTUS_PATH: /var/lib/lotus
+    RESET_PERCENTAGE: "90"
+  resources:
+    requests:
+      memory: 128Mi
+      cpu: 0.5
+  volumeMounts:
+  - *lotusPathVolumeMount
 
-    ## Golang vars
-    GOLOG_FORMAT: json
+#########3
 
-    ## Jaeger Agent configuration
-    LOTUS_JAEGER_AGENT_HOST:
-      valueFrom:
-        fieldRef:
-          apiVersion: v1
-          fieldPath: status.hostIP
-    LOTUS_JAEGER_AGENT_PORT: "6831"
-  extraEnv: {}
+global:
+  # -- Set an override for the prefix of the fullname
+  nameOverride:
+  # -- Set the entire name definition
+  fullnameOverride:
+  # -- Set additional global labels. Helm templates can be used.
+  labels: {}
+  # -- Set additional global annotations. Helm templates can be used.
+  annotations: {}
 
-# ipfs configuration
-# This is not enabled by default
-# When enabled, an IPFS daemon will run as a sidecar.
-# The API endpoint of this sidecar is reachable by
-# the dns name "ipfs". Using a multiaddr, it is reachable
-# with this string: /dns/ipfs/tcp/5001/http
-ipfs:
-  enabled: false
-  image: ipfs/go-ipfs:latest
-  imagePullPolicy: Always
-  size: 10Gi
+# image:
+#   # -- image repository
+#   repository:
+#   # -- image tag
+#   tag:
+#   # -- image pull policy
+#   pullPolicy:
+
+# # -- Set image pull secrets
+# imagePullSecrets: []
+
+# # -- Override the command(s) for the default container
+# command: []
+# # -- Override the args for the default container
+# args: []
+
+# # -- Set annotations on the pod
+# podAnnotations: {}
+
+# # -- Set labels on the pod
+# podLabels: {}
+
+# # -- Add a Horizontal Pod Autoscaler
+# # @default -- <disabled>
+# autoscaling:
+#   enabled: false
+#   target:  # deploymentname
+#   minReplicas:  # 1
+#   maxReplicas:  # 100
+#   targetCPUUtilizationPercentage:  # 80
+#   targetMemoryUtilizationPercentage:  # 80
+
+# serviceAccount:
+#   # -- Specifies whether a service account should be created
+#   create: false
+
+#   # -- Annotations to add to the service account
+#   annotations: {}
+
+#   # -- The name of the service account to use.
+#   # If not set and create is true, a name is generated using the fullname template
+#   name: ""
+
+# # -- Specifies whether a service account token should be automatically mounted.
+# automountServiceAccountToken: true
+
+# # -- Use this to populate a secret with the values you specify.
+# # Be aware that these values are not encrypted by default, and could therefore visible
+# # to anybody with access to the values.yaml file.
+# secret: {}
+#   # PASSWORD: my-password
 
 
-# Do you want prometheus monitoring with prometheus-operator?
-prometheus:
-  serviceMonitor: false
-  path: /metrics
-  port: ""
+# # -- Main environment variables. Template enabled.
+# # Syntax options:
+# # A) TZ: UTC
+# # B) PASSWD: '{{ .Release.Name }}'
+# # C) PASSWD:
+# #      configMapKeyRef:
+# #        name: config-map-name
+# #        key: key-name
+# # D) PASSWD:
+# #      valueFrom:
+# #        secretKeyRef:
+# #          name: secret-name
+# #          key: key-name
+# #      ...
+# # E) - name: TZ
+# #      value: UTC
+# # F) - name: TZ
+# #      value: '{{ .Release.Name }}'
+# env:
 
-# Bring your own filebeat.
-# The network where you are running might already have great log hadling.
-# If it does, there's no need to enable this. For those who need customized
-# log handling, this is for you.
-#
-# Enabling filebeat will install a filebeat sidecar.
-# Lotus will write logs to a file so it can be handled by filebeat. If your
-# application writes log files as well, filebeat can pick them up.
-#
-# Some people might not want to include secrets (API tokens, etc) in a values
-# file. If this is you, enable "filebeat.external". When this is enabled,
-# the rest of the filebeat options are ignored, and you should create the secret
-# with your filebeat configuration on your own.
-# hint: see templates/filebeat-config.yaml
-#
-# The example config works with logz.io.
-# Configuration tips:
-# hint: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html
-filebeat:
-  enabled: false
-  external: false
-  externalSecret: yoursecretname
-  image: store/elastic/filebeat:7.13.2
-  path: /var/log/app
-  secrets:
-    - name: logzio-certs
-      keys:
-        SectigoRSADomainValidationSecureSerA.crt: |
-          -----BEGIN CERTIFICATE-----
-          MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
-          iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
-          cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
-          BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
-          MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
-          BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
-          ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
-          VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
-          AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
-          TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
-          eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
-          oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
-          Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
-          uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
-          BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
-          +ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
-          A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
-          CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
-          LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
-          BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
-          bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
-          L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
-          ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
-          7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
-          H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
-          RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
-          xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
-          sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
-          l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
-          6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
-          LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
-          yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
-          00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
-          -----END CERTIFICATE-----
-      mount: /certs
-  config: |
-    ############################# Filebeat #####################################
-    filebeat.inputs:
-    - type: log
-      paths:
-        - /var/log/app/*
-        - /var/lib/lotus/journal/*
-      fields:
-        logzio_codec: plain
-        token: abc123
-        type: lotus
-      fields_under_root: true
-      encoding: utf-8
-      ignore_older: 3h
-    processors:
-    - rename:
-        fields:
-         - from: "agent"
-           to: "beat_agent"
-        ignore_missing: true
-    - rename:
-        fields:
-         - from: "log.file.path"
-           to: "source"
-        ignore_missing: true
+# # -- Secrets and/or ConfigMaps that will be loaded as environment variables.
+# # [[ref]](https://unofficial-kubernetes.readthedocs.io/en/latest/tasks/configure-pod-container/configmap/#use-case-consume-configmap-in-environment-variables)
+# envFrom: []
+# # - configMapRef:
+# #     name: config-map-name
+# # - secretRef:
+# #     name: secret-name
 
-    ############################# Output ##########################################
-    output:
-      logstash:
-        hosts:
-          - "listener.logz.io:5015"
-        ssl:
-          certificate_authorities:
-            - "/certs/SectigoRSADomainValidationSecureSerA.crt"
+# # -- Custom priority class for different treatment by the scheduler
+# priorityClassName:  # system-node-critical
+
+# # -- Allow specifying a runtimeClassName other than the default one (ie: nvidia)
+# runtimeClassName:  # nvidia
+
+# # -- Allows specifying a custom scheduler name
+# schedulerName:  # awkward-dangerous-scheduler
+
+# # -- Allows specifying explicit hostname setting
+# hostname:
+
+# # -- When using hostNetwork make sure you set dnsPolicy to `ClusterFirstWithHostNet`
+# hostNetwork: false
+
+# # -- Defaults to "ClusterFirst" if hostNetwork is false and "ClusterFirstWithHostNet" if hostNetwork is true.
+# dnsPolicy:  # ClusterFirst
+
+# # -- Optional DNS settings, configuring the ndots option may resolve nslookup issues on some Kubernetes setups.
+# dnsConfig: {}
+# #   options:
+# #     - name: ndots
+# #       value: "1"
+
+# # -- Enable/disable the generation of environment variables for services.
+# # [[ref]](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service)
+# enableServiceLinks: true
+
+# # -- Configure the Security Context for the Pod
+# podSecurityContext: {}
+
+# # -- Configure the Security Context for the main container
+# securityContext: {}
+
+# # -- Configure the lifecycle for the main container
+# lifecycle: {}
+
+# # -- Specify any initContainers here as dictionary items. Each initContainer should have its own key.
+# # The dictionary item key will determine the order. Helm templates can be used.
+# initContainers: {}
+
+# # -- Specify any additional containers here as dictionary items. Each additional container should have its own key.
+# # Helm templates can be used.
+# additionalContainers: {}
+
+# # -- Probe configuration
+# # -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
+# # @default -- See below
+# probes:
+#   # -- Liveness probe configuration
+#   # @default -- See below
+#   liveness:
+#     # -- Enable the liveness probe
+#     enabled: true
+#     # -- Set this to `true` if you wish to specify your own livenessProbe
+#     custom: false
+#     # -- The spec field contains the values for the default livenessProbe.
+#     # If you selected `custom: true`, this field holds the definition of the livenessProbe.
+#     # @default -- See below
+#     spec:
+#       initialDelaySeconds: 0
+#       periodSeconds: 10
+#       timeoutSeconds: 1
+#       failureThreshold: 3
+
+#   # -- Redainess probe configuration
+#   # @default -- See below
+#   readiness:
+#     # -- Enable the readiness probe
+#     enabled: true
+#     # -- Set this to `true` if you wish to specify your own readinessProbe
+#     custom: false
+#     # -- The spec field contains the values for the default readinessProbe.
+#     # If you selected `custom: true`, this field holds the definition of the readinessProbe.
+#     # @default -- See below
+#     spec:
+#       initialDelaySeconds: 0
+#       periodSeconds: 10
+#       timeoutSeconds: 1
+#       failureThreshold: 3
+
+#   # -- Startup probe configuration
+#   # @default -- See below
+#   startup:
+#     # -- Enable the startup probe
+#     enabled: true
+#     # -- Set this to `true` if you wish to specify your own startupProbe
+#     custom: false
+#     # -- The spec field contains the values for the default startupProbe.
+#     # If you selected `custom: true`, this field holds the definition of the startupProbe.
+#     # @default -- See below
+#     spec:
+#       initialDelaySeconds: 0
+#       timeoutSeconds: 1
+#       ## This means it has a maximum of 5*30=150 seconds to start up before it fails
+#       periodSeconds: 5
+#       failureThreshold: 30
+
+# termination:
+#   # -- Configure the path at which the file to which the main container's termination message will be written.
+#   # -- [[ref](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle-1)]
+#   messagePath:
+
+#   # -- Indicate how the main container's termination message should be populated.
+#   # Valid options are `File` and `FallbackToLogsOnError`.
+#   # -- [[ref](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle-1)]
+#   messagePolicy:
+
+#   # -- Duration in seconds the pod needs to terminate gracefully
+#   # -- [[ref](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle)]
+#   gracePeriodSeconds:
+
+# # -- Configure the services for the chart here.
+# # Additional services can be added by adding a dictionary key similar to the 'main' service.
+# # @default -- See below
+
+
+# # -- Used in conjunction with `controller.type: statefulset` to create individual disks for each instance.
+# volumeClaimTemplates: []
+# # - name: data
+# #   mountPath: /data
+# #   accessMode: "ReadWriteOnce"
+# #   size: 1Gi
+# # - name: backup
+# #   mountPath: /backup
+# #   subPath: theSubPath
+# #   accessMode: "ReadWriteOnce"
+# #   size: 2Gi
+# #   storageClass: cheap-storage-class
+
+
+# # -- Set the resource requests / limits for the main container.
+# resources: {}
+#   ## We usually recommend not to specify default resources and to leave this as a conscious
+#   ## choice for the user. This also increases chances charts run on environments with little
+#   ## resources, such as Minikube. If you do want to specify resources, uncomment the following
+#   ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
+#   # limits:
+#   #   cpu: 100m
+#   #   memory: 128Mi
+#   # requests:
+#   #   cpu: 100m
+#   #   memory: 128Mi
