fix(lily): Make snapshot download conditioned on import success

diff --git a/charts/lily/templates/statefulset.yaml b/charts/lily/templates/statefulset.yaml
--- a/charts/lily/templates/statefulset.yaml
+++ b/charts/lily/templates/statefulset.yaml
@@ -66,24 +66,27 @@ spec:
               exit 0
             fi
 
-            echo "*** Downloading snapshot from url {{ .Values.daemon.importSnapshot.url }}..."
-            curl -sL -o ./aria2-1.36.0.deb https://github.com/q3aql/aria2-static-builds/releases/download/v1.36.0/aria2-1.36.0-linux-gnu-64bit-build1.deb
-            dpkg -i ./aria2-1.36.0.deb
-            rm ./aria2-1.36.0.deb
+            if [ ! -f "/var/lib/lily/datastore/snapshot.car" ]; then
+              echo "*** Downloading snapshot from url {{ .Values.daemon.importSnapshot.url }}..."
+              curl -sL -o ./aria2-1.36.0.deb https://github.com/q3aql/aria2-static-builds/releases/download/v1.36.0/aria2-1.36.0-linux-gnu-64bit-build1.deb
+              dpkg -i ./aria2-1.36.0.deb
+              rm ./aria2-1.36.0.deb
 
-            (cd /var/lib/lily/datastore && time aria2c -x16 -k1M -o snapshot.car {{ .Values.daemon.importSnapshot.url }}
-            status=$?
-            if [ $status -ne 0 ]; then
-              rm /var/lib/lily/datastore/snapshot.car
-              echo "...download failed: $status"
-              exit $status
+              (cd /var/lib/lily/datastore && time aria2c -x16 -k1M -o snapshot.car {{ .Values.daemon.importSnapshot.url }})
+              status=$?
+              if [ $status -ne 0 ]; then
+                rm /var/lib/lily/datastore/snapshot.car
+                echo "...download failed: $status"
+                exit $status
+              fi
             fi
+
 
             echo "*** Importing snapshot..."
             lily init --import-snapshot=/var/lib/lily/datastore/snapshot.car
             status=$?
-            rm /var/lib/lily/datastore/snapshot.car
             if [ $status -eq 0 ]; then
+              rm /var/lib/lily/datastore/snapshot.car
               touch "/var/lib/lily/datastore/_imported"
             fi
 
