feat(lily): Optimize snapshot import download (#129)
* feat(lily): Optimize snapshot import download

* fix(lily): Make snapshot download conditioned on import success

* chore(lily): Update version to alpha of next version release

Co-authored-by: Mike Greenberg <placer14@users.noreply.github.com>

diff --git a/charts/lily/templates/statefulset.yaml b/charts/lily/templates/statefulset.yaml
--- a/charts/lily/templates/statefulset.yaml
+++ b/charts/lily/templates/statefulset.yaml
@@ -45,6 +45,8 @@ spec:
         command: ["/bin/sh", "-c"]
         args:
           - |
+            set -x
+
             # generate 6-char random uid to be used in job report names
             if [ ! -f "/var/lib/lily/uid" ]; then
               tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w ${1:-6} | head -n 1 > /var/lib/lily/uid
@@ -57,8 +59,40 @@ spec:
 
             # import snapshot if enabled
             {{- if .Values.daemon.importSnapshot.enabled }}
-              {{- include "sentinel-lily.chainImportArgs" . | indent 10 }}
-            {{- else }}
+            if [ -f "/var/lib/lily/datastore/_imported" ]; then
+              echo "Skipping import, found /var/lib/lily/datastore/_imported file."
+              echo "Ensuring secrets have correct permissions."
+              chmod 0600 /var/lib/lily/keystore/*
+              exit 0
+            fi
+
+            if [ ! -f "/var/lib/lily/datastore/snapshot.car" ]; then
+              echo "*** Downloading snapshot from url {{ .Values.daemon.importSnapshot.url }}..."
+              curl -sL -o ./aria2-1.36.0.deb https://github.com/q3aql/aria2-static-builds/releases/download/v1.36.0/aria2-1.36.0-linux-gnu-64bit-build1.deb
+              dpkg -i ./aria2-1.36.0.deb
+              rm ./aria2-1.36.0.deb
+
+              (cd /var/lib/lily/datastore && time aria2c -x16 -k1M -o snapshot.car {{ .Values.daemon.importSnapshot.url }})
+              status=$?
+              if [ $status -ne 0 ]; then
+                rm /var/lib/lily/datastore/snapshot.car
+                echo "...download failed: $status"
+                exit $status
+              fi
+            fi
+
+
+            echo "*** Importing snapshot..."
+            lily init --import-snapshot=/var/lib/lily/datastore/snapshot.car
+            status=$?
+            if [ $status -eq 0 ]; then
+              rm /var/lib/lily/datastore/snapshot.car
+              touch "/var/lib/lily/datastore/_imported"
+            fi
+
+            echo "Ensuring secrets have correct permissions."
+            chmod 0600 /var/lib/lily/keystore/*
+            exit $status
             {{- end }}
         env:
         - name: GOLOG_LOG_FMT
